package nl.whitehorses.rules;

import nl.whitehorses.sbcc.eventprocessor.model.CaseEvent;
import nl.whitehorses.sbcc.eventprocessor.model.CaseAction;
import nl.whitehorses.sbcc.eventprocessor.model.MilestoneAction;
import nl.whitehorses.sbcc.eventprocessor.model.ActivityAction;

global nl.whitehorses.sbcc.eventprocessor.model.CaseAction caseAction;
dialect "mvel"

rule "Activity Action"
	when
		caseEvent:CaseEvent(eventType=="ACTIVITY_EVENT")
	then
	    ActivityAction activityAction = new ActivityAction();
        activityAction.setActivityName(caseEvent.getActivityEvent().getActivityName());
        activityAction.setAction(caseEvent.getActivityEvent().getActivityEvent());
		caseAction.setActivityAction(activityAction);
	end

rule "Milestone Action"
	when
		caseEvent:CaseEvent(eventType=="MILESTONE_EVENT")
	then
        MilestoneAction milestoneAction = new MilestoneAction();
        milestoneAction.setMilestoneName(caseEvent.getMilestoneEvent().getMilestone());
        milestoneAction.setAction(caseEvent.getMilestoneEvent().getMilestoneEvent());
        caseAction.setMilestoneAction(milestoneAction);
	end
